# ansible-pull setup
#
---
- remote_user: fsavoia
  hosts: all
  become: true

  vars:
    # schedule is fed directly to cron
    schedule: "* {{ random_hour }} * * *"

    # User to run ansible-pull as from cron
    cron_user: root

    # File that ansible will use for logs
    logfile: /var/log/ansible-pull.log

    # Directory to where repository will be cloned
    workdir: /var/lib/ansible/local

    repo_url: https://github.com/fsavoia/ansible-playbooks.git

    playbook_file: get_os.yaml

  tasks:
    # - name: Install ansible
    #   yum: pkg=ansible state=installed

    - name: Create local directory to work from
      file: path={{workdir}} state=directory owner=root group=root mode=0751

    # - name: Copy ansible inventory file to client
    #   copy: src=/etc/ansible/hosts dest=/etc/ansible/hosts
    #     owner=root group=root mode=0644

    - name: Create crontab entry to clone/pull git repository
      template: src=templates/etc_cron.d_ansible-pull.j2 dest=/etc/cron.d/ansible-pull owner=root group=root mode=0644

    - name: Create logrotate entry for ansible-pull.log
      template: src=templates/etc_logrotate.d_ansible-pull.j2 dest=/etc/logrotate.d/ansible-pull owner=root group=root mode=0644
